runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
  static_files: dist/\1
  upload: dist/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
- url: /
  static_dir: dist
  secure: always